version: '3.7'
services:
  go:
    container_name: go-webservice
    build:
      context: './docker'
      target: 'develop'
    volumes:
      - './:/go-webservice/'
    env_file:
      - .env
    environment:
      - ENV1=${ENV1}
      - ENV2=${ENV2}
      - LOG_FILE_LOCATION=${LOG_FILE_LOCATION}
    ports:
      - 8080:8080
    working_dir: '/go-webservice/'
    command: ['/bin/sh', '-c', 'tail -f /dev/null']
    restart: always
